### ISSUE TITLE
Is session_id just any value?

### ISSUE THREAD

**Issue by produdez** [dirtyg2120/thesis-backend#30]
Found in #29 
Tests show that any `session_id` can be used to send report?
- Should this be the case?
- What's the use of `secret` then?
- Not sure if this is expected behaviour or bad-security

More detail in PR

**Comment by phhai-hcmut** [comment]
No, we should save issued session IDs in database, but I have not implemented it yet.

**Comment by produdez** [comment]
> No, we should save issued session IDs in database, but I have not implemented it yet.

Did you forget to implement or dint think of it?
