### ISSUE TITLE
Report when TwitterUser is cleared bug

### ISSUE THREAD

**Issue by produdez** [dirtyg2120/thesis-backend#31]
Found in #29 

If TwitterUser is already deleted, user suppose to always re-check before reporting.

But currently, if user report an account and after that `TwitterUser` is cleared by background task, the old report will be re-used

More detail in PR

**Comment by produdez** [comment]
@dirtyg2120 you

**Comment by dirtyg2120** [comment]
"re-used" in your term means "if that user/other user report that account again, it will get the old one in DB, although `TwitterUser` is not exist", right?

In that case, I think there're 2 ways:
1. Also delete report in background task.
2. When send report, also check if that twitter account exist in `TwitterUser`.

**Comment by dirtyg2120** [comment]
> @dirtyg2120 you

saw it :V, u dont need to re-tag. What an unhealthy man, report bug at 1AM :V

**Comment by produdez** [comment]
I oversleept at noooon stop judging :v

**Comment by produdez** [comment]
> "re-used" in your term means "if that user/other user report that account again, it will get the old one in DB, although `TwitterUser` is not exist", right?

Correct.  U got it exactly

**Comment by produdez** [comment]
> 1. Also delete report in background task.

No we cant do num1 
> 2. When send report, also check if that twitter account exist in `TwitterUser`.

### This seems like the correct approach. 
So my thoughts on the flow is as follows:
1. If  account not in `TwitterUser` -> meaning all reports related to this account is also "locked" (expired for reporting)
2. Then in that case reporting the account must return `404 account not checked` error, forcing user to recheck
3. But then after account is `re-checked` and added to `TwitterUser`
4. We must somehow check and know that when user report this `re-checked` account, a new `Report` should be created
5. And `NOT` add count to any older, expired `Reports`

**As for step 4.** We can check that an account is new and `not reported` (meaning we have no reports avalable that's up-to-date with this account - including reports with same account_id) by several approaches:
1. Time stamp compare the `TwitterUser` and all same id `Reports`
2. A simpler way is just add a new field to `TwitterUser` called `reported` or sth. This makes sure all newly checked account is not reported and we dont need to implement long 🍑 logics

@dirtyg2120 @phhai-hcmut  wa cha think?

**Comment by dirtyg2120** [comment]
I think add `reported` field is a good way if we use your flow. But what to do with the expired reports, will it be deleted?

**Comment by produdez** [comment]
No i think we keep all reports. Each report is different `snapshot of account`.
