### ISSUE TITLE
URL input validation changed

### ISSUE THREAD

**Issue by produdez** [dirtyg2120/thesis-backend#33]
Found in #29 when merging #27 
Check/Detail url input
- Before: allow both `https://twitter.com/username` and `twitter.com/username`
- Currently: now allowing half url `twitter.com/username`

**Comment by phhai-hcmut** [comment]
What do you mean?

**Comment by produdez** [comment]
i meant get `api/check/?url=twitter.com/username` is not allowed currently but before it was

**Comment by phhai-hcmut** [comment]
I don't understand why we allow that format at all

**Comment by produdez** [comment]
I'll just tag @dirtyg2120 and let you guys figure it out :V

**Comment by dirtyg2120** [comment]
It's not wrong at all, so i include it :V

**Comment by dirtyg2120** [comment]
why user can not type: `twitter.com/username` on Check box ?

**Comment by phhai-hcmut** [comment]
Who wanna type `twitter.com/username`? Either they just type the username or copy/paste the full URL

**Comment by dirtyg2120** [comment]
@produdez if no one type like that, u can close this issue then :)))

**Comment by produdez** [comment]
Kay i'll close issue when i delete the related test case later.
