### ISSUE TITLE
Data model for ML Service

### ISSUE THREAD

**Issue by dirtyg2120** [dirtyg2120/thesis-backend#34]
This is all the feature @dfighter1312 tell me that he gonna need. So I think we will have to adjust the `TwitterUser` and `Tweet` model.
Here is a summary table for easier track. All of these attributes can be scraped with Twitter API so not much problem then, but let's discuss more with Đôrê in the next meeting before implement it.

**`TwitterUser`**
|ML Model|Current DB Model|Status|
|---|---|---|
|`id`                       |`id`| :heavy_check_mark:  |
|`statuses_count`  |`tweets_count`| :heavy_check_mark:  |
|`followers_count` |`followers_count`| :heavy_check_mark:  |
|`friends_count`    |`followings_count`| :heavy_check_mark: |
|`favorites_count` |`favorites_count`| :heavy_check_mark: |
|`listed_count`      |`listed_count`| :heavy_check_mark: |
|`default_profile`  |`default_profile`| :heavy_check_mark: |
|`default_profile_image`|`default_profile_image`| :heavy_check_mark: |
|`protected`          |`protected`| :heavy_check_mark: |
|`verified`             |`verified`| :heavy_check_mark: |
|`created_at`        |`created_at`| :heavy_check_mark: |
|`name`                |`name`| :heavy_check_mark: |
|`screen_name`   |`username`| :heavy_check_mark: |
|`description`        |`description`| :heavy_check_mark: |
|`crawled_at`        |`timestamp`| :heavy_check_mark: |
||`banner`| :heavy_check_mark: |
||`avatar`| :heavy_check_mark: |
||`tweets`| :heavy_check_mark: |
||`score`| :heavy_check_mark: |

**`Tweet`**
|ML Model|Current DB Model|Status|
|---|---|---|
|`id`|`id`| :heavy_check_mark: |
|`text`|`text`| :heavy_check_mark: |
|`user_id`|  | :heavy_check_mark: |
|`in_reply_to_status_id`|| :heavy_check_mark: |
|`retweeted_status_id`|| :heavy_check_mark: |
||`created_at`| :heavy_check_mark: |

**Comment by phhai-hcmut** [comment]
We should consistently use terminology in API v2, i.e., `tweet` instead of `status`

**Comment by produdez** [comment]
did you just assign everyone but yourself mfuker? @dirtyg2120

**Comment by dirtyg2120** [comment]
@produdez i assign for notification :V, not for work :V

**Comment by dirtyg2120** [comment]
Kay so i'll do this thing
