### ISSUE TITLE
ML Service is here !!!

### ISSUE THREAD

**Issue by dirtyg2120** [dirtyg2120/thesis-backend#39]
In short, there are 2 works:
1. Read this [Data Retrieval Path](https://docs.google.com/document/d/1nSw99q2fQl4nlPRwjGq8z8Qv_ueSoIJQK6C5wuaxLcE/edit?fbclid=IwAR18NleRtsn6_yziZ308eFYMM0lsg_ARTZ61-YfBGjq-5ZwP12G_x4oVdFg). I'm not really understand, so if u guys can, explain it to me :))))), otherwise we make a meet.
2. ML Repo: [hcmut-epfl/SOBOG](https://github.com/hcmut-epfl/SOBOG/tree/experiment). Branch: experiment.

**Comment by produdez** [comment]
I ummmm, dont understand s*** 🥉
