### ISSUE TITLE
Consider rename `TwitterUser`

### ISSUE THREAD

**Issue by produdez** [dirtyg2120/thesis-backend#43]
I find this model/schema naming is starting to get more confusing the more we use it.

What do u guys think? @dirtyg2120 @phhai-hcmut

**Comment by dirtyg2120** [comment]
do u have any suggestions for the name?

**Comment by produdez** [comment]
@phhai-hcmut

**Comment by phhai-hcmut** [comment]
Account maybe?

**Comment by produdez** [comment]
Account is same as TwitterUser :v

**Comment by phhai-hcmut** [comment]
So what do you want?

**Comment by produdez** [comment]
analysis/result/analysis-result/check-result/bot-prediction/prediction i dunno :v

**Comment by dirtyg2120** [comment]
@produdez  in your list, i think **check-result** is the only suitable

**Comment by phhai-hcmut** [comment]
I vote for BotPrediction

**Comment by produdez** [comment]
:v some one call dung~ sama to pick im lazy :v

**Comment by dirtyg2120** [comment]
@dfighter1312 :v

**Comment by produdez** [comment]
I dont think he's active here tho :0

**Comment by dfighter1312** [comment]
What TwitterUser orginally is? :D

**Comment by produdez** [comment]
userinfo + bot score

**Comment by dfighter1312** [comment]
I think bot pred or bot response (if you are referring to a schema) is ok :)) check-result is closest to its meaning (?) but sound somehow less fancy :))

**Comment by produdez** [comment]
Final: `BotPred`

**Comment by phhai-hcmut** [comment]
What does `Pred` mean?

**Comment by produdez** [comment]
`BotPrediction`***
